version: '3'
services:
  sqlite:
    image: "nouchka/sqlite3"
    restart: always
  backend:
    container_name: backend
    build: ./server/
    restart: always
    ports:
      - "6200:6200"
    volumes:
      - ./server:/usr/src/app
    depends_on:
      - sqlite
  frontend:
    container_name: frontend
    build: ./client/
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
    depends_on:
      - backend